### ISSUE TITLE
Dockerfile arguments

### ISSUE THREAD

**Issue by mattias-kindborg-at-work** [AxisCommunications/acap-native-sdk#14]
What is the benefit of having `ARCH` and `REPO` as Dockerfile arguments?

When it comes to `ARCH`, haven't we already decided on the architecture by selecting the correct Dockerfile among the alternatives `Dockerfile.aarch64` and `Dockerfile.armv7hf`?

When it comes to `REPO`, is a common scenario to choose another repository than the default to pull the images from?

The reason I'm asking is because having these arguments makes me believe that there's something missing to the puzzle, something I doesn't understand, that I will invest time into figuring out.

(This issue is valid for `acap-native-sdk-examples`, `acap-computer-vision-sdk` and `acap-computer-vision-sdk-examples` as well)

**Comment by mikaelli-axis** [comment]
The ARCH question is primarily a stylistic choice, if having individual Dockerfiles or parameterising them using build args is the better option depends on what building automation tool you use. Having REPO as an argument simplifies using your own builds of images if you are adding to the official axisecp/* ones. Again maybe more of a style issue than technical.
