### ISSUE TITLE
Automatically upgrading Dockerfiles

### ISSUE THREAD

**Issue by mattias-kindborg-at-work** [AxisCommunications/acap-native-sdk#15]
When it comes to dependencies we've had great success with using Renovate to automatically create new pull requests when new versions of dependencies are released.

Would automatically upgrading the base images found in the Dockerfiles be of benefit, or do you already have a well functioning process where the Dockerfiles are updated when new versions of the base images are released?

(This issue is valid for `acap-native-sdk-examples`, `acap-computer-vision-sdk` and `acap-computer-vision-sdk-examples` as well)

**Comment by mikaelli-axis** [comment]
Using Renovate is definitely an option to consider, though we are considering a few different options for how to handle cross-architecture builds and I think we'll postpone introducing other tools before we have sorted that question out.
