### ISSUE TITLE
Question: which SDK and compiler to use for Ambarella CV25

### ISSUE THREAD

**Issue by maggybaetens** [AxisCommunications/acap-native-sdk#22]
Hi, 
We've been asked by a customer to integrate our solution on a M2035-LE with chipset Ambarella CV25.
However in your description of SDK4.x, I don't see SDK4.x supports CV25. 

https://axiscommunications.github.io/acap-documentation/docs/api/native-api.html

What are the tools we need to integrate our ACAP on CV25 chipset?
Can you provide us the information we need to do this?

Thanks,
Maggy

**Comment by pataxis** [comment]
Hi, thanks for contacting us. The persons working on this are away this week, but we'll get back to you next week.

**Comment by pataxis** [comment]
The information I have is that the latest releases of the `aarch64` ACAP Native SDK can be used to build applications for CV25. However, documentation about platform specific functionality (specifically DL parts) has not yet been published and I can't give an exact date for when it will be available, but earlier than end of summer vacation is not likely.

**Comment by pataxis** [comment]
CV25 example adaption was made in [ACAP 4.4](https://axiscommunications.github.io/acap-documentation/docs/release-notes/4.4.html) release and as mentioned before it's the `aarch64` that's used.
