### ISSUE TITLE
OpenSSL removed from dockerfile ?

### ISSUE THREAD

**Issue by narcdev** [AxisCommunications/acap-native-sdk#50]
Hey,

I'm wondering why you remove OpenSSL from the docker file ? Is it not possible to keep it so we can use it ?

Thanks a lot for your answer !

Best Regards,

**Comment by narcdev** [comment]
Hey,

Thanks a lot for your answer. 

Is there any plan to make OpenSSL or OpenVPN supported by the SDK ?

**Comment by pataxis** [comment]
There's no set plan today, but I can say that it's considered. OpenSSL 3 would likely be the candidate.

**Comment by pataxis** [comment]
Hi @narcdev , a follow-up, in [ACAP 4.14](https://axiscommunications.github.io/acap-documentation/docs/release-notes/4.14.html) we have released OpenSSL.
