### ISSUE TITLE
AxParameter example missing

### ISSUE THREAD

**Issue by tpatora** [AxisCommunications/acap-native-sdk#51]
The AxParameter example is missing. Are ACAP 3 examples compatible with acap-native-sdk?

**Comment by pataxis** [comment]
Hi @tpatora , thank you for your question.

These are the supported APIs in the ACAP Native SDK https://axiscommunications.github.io/acap-documentation/docs/api/native-sdk-api.html.
Other libraries that can be found inside the SDK are not supported should not be depended on.

ACAP 3 examples ([acap3-examples](https://github.com/AxisCommunications/acap3-examples)) are not compatible with ACAP 4 example ([acap-native-sdk-examples](https://github.com/AxisCommunications/acap-native-sdk-examples)).

**Comment by pataxis** [comment]
@tpatora A follow-up, we have recently launched axparameter as a supported API in ACAP version [4.13 release](https://axiscommunications.github.io/acap-documentation/docs/release-notes/4.13.html) where ACAP Native SDK has version 1.13.
